### ISSUE TITLE
MessageManager#sendMessage文本消息无法发送, 且回调函数不执行

### ISSUE THREAD

**Issue by yuxiangxin** [OpenIMSDK/Open-IM-SDK-Android#11]
API: `io.openim.android.sdk.manager.MessageManager#sendMessage(OnMsgSendCallback base, Message message, String recvUid, String recvGid, boolean onlineUserOnly)`
发送空消息会正常走onError回调
![debug](https://user-images.githubusercontent.com/19987236/140618699-faea4faa-c38d-4f5b-9c6a-6ee625b16b1c.gif)

**Comment by hrxiang** [comment]
我这里测试完全可以，你是不是使用有问
![WeChataba33d0fe17fa81c4abdd5ef3f02adfe](https://user-images.githubusercontent.com/7018230/141717450-515a5294-e88b-43f9-ac2a-bd15c92695a9.png)
![WeChata43a34d7aa44c78de950152e14c63491](https://user-images.githubusercontent.com/7018230/141717464-c39d1d94-6f3c-44ed-81eb-7cb9cf8d7994.png)
![WeChatc42539aed506061b57c3572f4b0ec01e](https://user-images.githubusercontent.com/7018230/141717471-f138fa5d-cacc-473c-b626-1cc9bbe4e0ff.png)
题

**Comment by hrxiang** [comment]
一直没回调就是服务器超时了，sdk设置了超时重试。

**Comment by yuxiangxin** [comment]
确实, 是我们服务端设置的有问题
