### ISSUE TITLE
io.openim:client-sdk 在哪个仓

### ISSUE THREAD

**Issue by liuyu520707** [OpenIMSDK/Open-IM-SDK-Android#16]
io.openim:client-sdk 在哪个仓

**Comment by dengxiaoyu** [comment]
如果我没理解错的话 ，你下载了 demo 之后 ，在项目下的 .gradle   的 repositories  和  allprojects下的 repositories 都有写了

**Comment by hrxiang** [comment]
> io.openim:client-sdk 在哪个仓

https://github.com/OpenIMSDK/Open-IM-SDK-Core.git

**Comment by liuyu520707** [comment]
> > io.openim:client-sdk 在哪个仓
> 
> https://github.com/OpenIMSDK/Open-IM-SDK-Core.git

这个能打包安卓的aar 吗？

**Comment by liuhuyun** [comment]
io.openim:client-sdk:1.2.0@aar  这个拉不下来

**Comment by hrxiang** [comment]
> io.openim:client-sdk:1.2.0@aar 这个拉不下来

请跟sdk保持同步更新。

**Comment by koushiyu** [comment]
> > > io.openim:client-sdk 在哪个仓
> > 
> > 
> > https://github.com/OpenIMSDK/Open-IM-SDK-Core.git
> 
> 这个能打包安卓的aar 吗？
 maven {
                    url 'http://121.37.25.71:8081/repository/maven-releases/'
                    allowInsecureProtocol = true
                }

**Comment by zhaoxianhua** [comment]
> io.openim:client-sdk 在哪个仓

请问确定由Open-IM-SDK-Core工程打出的包吗？我不知道是怎么弄的？

**Comment by hrxiang** [comment]
> > io.openim:client-sdk 在哪个仓
> 
> 请问确定由Open-IM-SDK-Core工程打出的包吗？我不知道是怎么弄的？

cd Open-IM-SDK-Core
make android/ios
