### ISSUE TITLE
获取会话列表APP崩溃

### ISSUE THREAD

**Issue by Topone** [OpenIMSDK/Open-IM-SDK-Android#19]
第一次获取会话列表，app崩溃，第二次进入就好了

OpenIMClient.getInstance().conversationManager.getAllConversationList(object : OnBase<List<ConversationInfo?>?> {
                override fun onError(code: Long, error: String) {}

                override fun onSuccess(data: List<ConversationInfo?>?) {
                }
            })

crash 信息：
E/Go: panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x792ca1eb50]
    goroutine 41 [running]:
    database/sql.(*Rows).Next(0x0, 0x792cf84ca9)
E/GoLog: panic: runtime error: invalid memory address or nil pointer dereference
E/Go: 	D:/Go/src/database/sql/sql.go:2835 +0x20
    open_im_sdk.(*UserRelated).getAllConversationListModel(0x792d580520, 0x792d194dc0, 0x4000098320, 0x0, 0x0, 0x0)
    	C:/Users/Admin/go/src/open_im_sdk/data_model.go:441 +0xd4
    open_im_sdk.(*UserRelated).GetAllConversationList.func1(0x792d580520, 0x792d19b2a0, 0x40001b9548)
    	C:/Users/Admin/go/src/open_im_sdk/open_im_sdk_conversation_msg.go:18 +0x20
    created by open_im_sdk.(*UserRelated).GetAllConversationList
E/GoLog: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x792ca1eb50]
E/Go: 	C:/Users/Admin/go/src/open_im_sdk/open_im_sdk_conversation_msg.go:17 +0x44
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 21009 (Thread-5), pid 18478 
I

**Comment by dengxiaoyu** [comment]
我之前也遇到过 ，我主要是会话 ，好友关系，消息，群组，每个管理器 都需要设置监听，设置监听之后就不会报错了。 你看看行不行

**Comment by Topone** [comment]
> 我之前也遇到过 ，我主要是会话 ，好友关系，消息，群组，每个管理器 都需要设置监听，设置监听之后就不会报错了。 你看看行不行

初始化的时候就需要设置全部监听？

**Comment by Topone** [comment]
> > 我之前也遇到过 ，我主要是会话 ，好友关系，消息，群组，每个管理器 都需要设置监听，设置监听之后就不会报错了。 你看看行不行
> 
> 初始化的时候就需要设置全部监听？

还真是。。。。。。得设置全部监听。。。在登录之前
