### ISSUE TITLE
目前碰到的问题

### ISSUE THREAD

**Issue by snacksnackgo** [OpenIMSDK/Open-IM-SDK-Android#21]
注册、登录、获取Token都正常，登录账号A和账号B后，已互为好友，然后分别设置addAdvancedMsgListener和setOnConversationListener，两个账号互发消息，sendMessage回调都成功，但addAdvancedMsgListener和setOnConversationListener有时候无响应，有时候收到消息后JNI层会崩溃而且频率比较高，还有获取好友getFriendList接口在app第一次打开时获取成功但是为空，重启后正常，测试环境为木木模拟器和夜神模拟器

**Comment by dengxiaoyu** [comment]
我之前也遇到过 ，会话 ，好友关系，消息，群组，每个管理器 都需要设置监听，设置监听之后就不会报错了。 你看看行不行

**Comment by Alicegril** [comment]
你好，請問你这个问题解决了吗？我现在也遇到了

**Comment by dengxiaoyu** [comment]
> 

每个管理器 都需要设置监听

**Comment by dengxiaoyu** [comment]
> 你好，請問你这个问题解决了吗？我现在也遇到了

每个管理器 都需要设置监听，就不会报错了，你看他的那个demo ,在第一个act 里面 给所以监听都实现了 之后 就行了
