### ISSUE TITLE
发现消息，走错误回调方法，但是这个消息 在历史记录里面能获取到 

### ISSUE THREAD

**Issue by dengxiaoyu** [OpenIMSDK/Open-IM-SDK-Android#24]
错误码是201  错误信息 是 kafka send msg err

**Comment by dengxiaoyu** [comment]
/**
  * 文本消息
  */
                    val v2: Message =
                        OpenIMClient.getInstance().messageManager.createTextMessage(binding.etChat.text.toString() + "")
                    sendMessage(v2)

  /**
     * 发送消息的方法
     */
    fun sendMessage(v2: Message) {
        OpenIMClient.getInstance().messageManager.sendMessage(
            object : OnMsgSendCallback {
                override fun onError(code: Long, error: String?) {
                    Log.e("IM发送失败", "onError: code" + Gson().toJson(code) + "/" + error)
                    if (208 == code.toInt()) {
                        ToastUtils.show(this@ChatDeatailPageActivity.resources.getString(R.string.groupnotexist))
                    }
                }

                @SuppressLint("NotifyDataSetChanged")
                override fun onSuccess(s: String?) {
                    binding.etChat.setText("")
                    chatlist.add(v2)
                    chatDetailPage!!.notifyDataSetChanged()
                    binding.recyclerChatDetail.scrollToPosition(chatDetailPage!!.itemCount - 1)
                    setNoReadMessageList(chatlist)//设置消息是否已读的
                }

                override fun onProgress(progress: Long) {

                }

            }, v2, uid, null, false
        )
    }

**Comment by hrxiang** [comment]
1. 发消息通过当前方法的callback回调。
2. 收消息通过全局监听器的onRecvNewMessage方法回调。
3. 创建消息后，在发送之前就应该将消息添加到list里，然后刷新界面，然后通过callback刷新状态：成功，失败，发送中，上传进度（图片，文件，视频）。
