### ISSUE TITLE
提bug前请看

### ISSUE THREAD

**Issue by hrxiang** [OpenIMSDK/Open-IM-SDK-Android#28]
SDK使用步骤
1，始化sdk
2，设置各种监听器
3，登录
4，其他操作。

所有操作必须保证已完成1，2，3这三个步骤之后进行。

初始化是否成功可以根据初始化返回的boolean值判断，也可以在调用login方法时查看控制台日志。

**Comment by hrxiang** [comment]
io.opeim.client-sdk：源码开源地址：https://github.com/OpenIMSDK/Open-IM-SDK-Core.git

**Comment by hrxiang** [comment]
该项目是go SDK的桥接代码，不是demo，运行看不到任何效果。

**Comment by liuhuyun** [comment]
Connect to 47.112.160.66:8081 [/47.112.160.66] failed: Connection timed out: connect
