### ISSUE TITLE
io.openim:client-sdk:1.4.4@aar CAN NOT FOUND

### ISSUE THREAD

**Issue by SamXiao** [OpenIMSDK/Open-IM-SDK-Android#29]
GOT ERROR WHEN I TRY TO RUN DEMO

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve io.openim:client-sdk:1.4.4.
     Required by:
         project :app > project :flutter_openim_sdk
      > Could not resolve io.openim:client-sdk:1.4.4.
         > Could not get resource 'https://dl.bintray.com/aweme-open-sdk-team/public/io/openim/client-sdk/1.4.4/client-sdk-1.4.4.pom'.
            > Could not GET 'https://dl.bintray.com/aweme-open-sdk-team/public/io/openim/client-sdk/1.4.4/client-sdk-1.4.4.pom'. Received status code 502 from server: Bad Gateway

**Comment by hrxiang** [comment]
> GOT ERROR WHEN I TRY TO RUN DEMO
> 
> * What went wrong:
>   Could not determine the dependencies of task ':app:processDebugResources'.
> 
> > Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
> > Could not resolve io.openim:client-sdk:1.4.4.
> > Required by:
> > project :app > project :flutter_openim_sdk
> > > Could not resolve io.openim:client-sdk:1.4.4.
> > > Could not get resource 'https://dl.bintray.com/aweme-open-sdk-team/public/io/openim/client-sdk/1.4.4/client-sdk-1.4.4.pom'.
> > > Could not GET 'https://dl.bintray.com/aweme-open-sdk-team/public/io/openim/client-sdk/1.4.4/client-sdk-1.4.4.pom'. Received status code 502 from server: Bad Gateway

gradle配置或版本的问题

**Comment by hrxiang** [comment]
```
  maven {
            allowInsecureProtocol = true
            url 'http://47.112.160.66:8081/repository/maven-releases'
        }
```
