### ISSUE TITLE
o.opeim.client-sdk

### ISSUE THREAD

**Issue by yghysdr** [OpenIMSDK/Open-IM-SDK-Android#32]
如公告： o.opeim.client-sdk：源码开源地址：https://github.com/OpenIMSDK/Open-IM-SDK-Core.git

如下java类在哪呢，Open_im_sdk 。整个open_im_sdk包下的java是没有找到

**Comment by hrxiang** [comment]
> 如公告： o.opeim.client-sdk：源码开源地址：https://github.com/OpenIMSDK/Open-IM-SDK-Core.git
> 
> 如下java类在哪呢，Open_im_sdk 。整个open_im_sdk包下的java是没有找到

自动转换在编译成aar包的时候

**Comment by yghysdr** [comment]
Open-IM-SDK-Core.git 整个工程不都是go开发的吗，用go编译成aar吗
