### ISSUE TITLE
登录返回 702

### ISSUE THREAD

**Issue by wedxz** [OpenIMSDK/Open-IM-SDK-Android#33]
![image](https://user-images.githubusercontent.com/16360512/156520806-46cedeeb-b752-4e92-86ec-a4ebcc70c800.png)

![1646293867(1)](https://user-images.githubusercontent.com/16360512/156520410-8d6e5587-50aa-47be-b716-d7f76cebe976.png)

获取的uid和token 16603404600_________________eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVSUQiOiIxNjYwMzQwNDYwMCIsIlBsYXRmb3JtIjoiTGludXgiLCJleHAiOjE2NDY4MTk5NzIsIm5iZiI6MTY0NjIxNTE3MiwiaWF0IjoxNjQ2MjE1MTcyfQ.eXYBKXN8cOZ2z3UuWboRLGlsSdTdpoJkUCfQrOVpviE

登录返回的错误信息
702_________________operationID[1646293913360], info[==> open_im_sdk/internal/login.CheckToken()@256: GetSelfUserInfoFromSvr failed 1646293913360: ==> open_im_sdk/internal/user.(*User).GetSelfUserInfoFromSvr()@141: 1646293913360: ==> open_im_sdk/pkg/common.CheckErrAndResp()@79: api resp failed: ==> open_im_sdk/pkg/network.Post2Api()@42:  post: ==> open_im_sdk/pkg/network.postLogic()@70: status code failed http://122.9.124.193:10000/user/get_self_user_info: 404 Not Found]

**Comment by hrxiang** [comment]
是不是 你注册的时候，im那块实际上没有注册成功。

**Comment by liuhuyun** [comment]
web 端可以登录成功

**Comment by liuhuyun** [comment]
注册用的auth/password接口
获取token用的auth/user_token接口

**Comment by hrxiang** [comment]
api注册：auth/password
api登录：auth/login

**Comment by liuhuyun** [comment]
![image](https://user-images.githubusercontent.com/16360512/156689015-55d89f64-3a31-4a67-a95e-00212b7810a3.png)
登录用的这个,看不到地址

**Comment by hrxiang** [comment]
> ![image](https://user-images.githubusercontent.com/16360512/156689015-55d89f64-3a31-4a67-a95e-00212b7810a3.png) 登录用的这个,看不到地址

获取token的时候用auth/login

**Comment by liuhuyun** [comment]
![image](https://user-images.githubusercontent.com/16360512/156692558-e0ea99c6-f412-40fc-9d02-260c67712a41.png)
不是这个?

**Comment by liuhuyun** [comment]
> > ![image](https://user-images.githubusercontent.com/16360512/156689015-55d89f64-3a31-4a67-a95e-00212b7810a3.png) 登录用的这个,看不到地址
> 
> 获取token的时候用auth/login

你说的这个接口在哪了,文档上没有啊

**Comment by hrxiang** [comment]
注册：:42233/auth/password
登录：:42233/auth/login


注册：:10000/auth/user_register
登录：:10000/auth/user_token

**Comment by liuhuyun** [comment]
> 注册：:42233/auth/password 登录：:42233/auth/login
> 
> 注册：:10000/auth/user_register 登录：:10000/auth/user_token

 
![image](https://user-images.githubusercontent.com/16360512/156711823-6b67a1ed-fc57-4202-b957-8c649a5f219a.png)

 这个不是获取用户token吗?

![image](https://user-images.githubusercontent.com/16360512/156711736-536cf399-c964-4a06-8b2b-22fe553ebed2.png)
登录不是用这个吗?
