### ISSUE TITLE
查询用户是否在IM中注册 返回 400

### ISSUE THREAD

**Issue by wedxz** [OpenIMSDK/Open-IM-SDK-Android#34]
{"errCode":400,"errMsg":"Key: 'paramsAccountCheck.UserIDList' Error:Field validation for 'UserIDList' failed on the 'required' tag"}

**Comment by hrxiang** [comment]
。。。你那个是后端使用的api，别把什么问题都提到移动端。。。。

**Comment by liuhuyun** [comment]
行吧,现在登录这个702 咋弄

**Comment by liuhuyun** [comment]
702啥意思啊,你们有错误码的信息吗?
