### ISSUE TITLE
接收到消息直接闪退

### ISSUE THREAD

**Issue by wedxz** [OpenIMSDK/Open-IM-SDK-Android#42]
![微信图片_20220516100218](https://user-images.githubusercontent.com/16360512/168507949-ac4e042a-2357-4738-ac49-731713ef4f83.png)

**Comment by hrxiang** [comment]
是按照文档步骤完成1，2，3个步骤在获取数据的吗

**Comment by liuhuyun** [comment]
对啊

**Comment by wedxz** [comment]
有解决办法吗?
