### ISSUE TITLE
Can OpenIMClient.getInstance().messageManager.setAdvancedMsgListener and related callbacks only be set once?

### ISSUE THREAD

**Issue by Goats2003** [openimsdk/open-im-sdk-android#48]
在classA里initSDK--设置回调监听---login登录（正常）-----logout登出---在新的实列类classB里initSDK--设置回调监听---login登录:此时回调里的类是第一次设置的classA导致部分监听回调异常，通过给ClassA和ClassB的tag对比发现，在退出登录后在新的实例里重新执行相关initSDK--设置回调监听---login登录流程时，回调里的数据是异常，登录及初始化等其它正常。如果说和Open_im_sdk或只能初始化一次的问题然后sdk里并没有uninit_sdk

**Comment by JINMUSENG** [comment]
Sdk是单例

**Comment by Oliver-WJ** [comment]
Added a method 'uninit_sdk',You can use it
