### ISSUE TITLE
Feature: <Feature Request Title>

### ISSUE THREAD

**Issue by 565204031** [openimsdk/open-im-sdk-android#54]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

你好，我们的App有这么一个需求，国外的用户需要init国外的url,国内的用户需要init url的需求。目前的SDK只能init一次，无法切换url。建议能不能像3.2ios SDK的版本一样，新增一个uninit的接口。

### Solution Description

新增一个uninit的接口。

### Benefits

可以动态切换url

**Comment by Oliver-WJ** [comment]
added
Please include io.openim:android-sdk:3.3.0+1@aar

**Comment by 565204031** [comment]
> added Please include io.openim:android-sdk:3.3.0+1@aar

升级了SDK后，登录成功后，一直回调onUserTokenExpired 这个接口，根本用不了。

**Comment by 565204031** [comment]
调用uninit 再次调用initSDK 并且设置了新的URL还是无法生效。麻烦看一下哈。
