### ISSUE TITLE
[BUG] The getAllConversationList function cannot retrieve the latest nickname and avatar

### ISSUE THREAD

**Issue by wozaihu** [openimsdk/open-im-sdk-android#60]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

When chatting with strangers, if the other party updates their nickname and avatar, the getAllConversationList function still retrieves the old avatar. When the other party sends me a message, the nickname and avatar included in the printed message are the new ones. However, in the ConversationInfo from getAllConversationList, the nickname and avatar of the other party are still the old ones.

**Comment by JauneQ** [comment]
It's normal. The getAllConversationList function will update your friends' info, the stranger's info will not be updated just like Wechat's. If you wanna to update it, you can try to use getUsersInfo function. GetUsersInfo funcation is [here](https://github.com/openimsdk/open-im-sdk-android/blob/main/OpenIM-SDK/src/main/java/io/openim/android/sdk/manager/UserInfoManager.java).
