### ISSUE TITLE
[BUG] 手机设置代理后，wsAddr访问服务器网络不通，导致android apk登录失败

### ISSUE THREAD

**Issue by lijrhw** [openimsdk/open-im-sdk-android#63]
### OpenIM Server Version

3.5.1

### Operating System and CPU Architecture

Windows (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

手机设置代理后，wsAddr访问服务器网络不通，导致android apk登录失败。
通过手机wifi接入代理配置及手机的android 代码设置代理都存在该问题。

**Comment by JauneQ** [comment]
We recommend that you upgrade yours to 3.8.1.
