### ISSUE TITLE
[错误]

### ISSUE THREAD

**Issue by luodanian** [openimsdk/open-im-sdk-android#75]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

macOS (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

 //openIM
    implementation 'io.openim:android-sdk:3.8.1@aar'
    implementation 'io.openim:core-sdk:3.5.1-alpha.7@aar'

**Comment by JauneQ** [comment]
#76

**Comment by luodanian** [comment]
How to solve this problem?

**Comment by JauneQ** [comment]
This issue has no detail about the error and no correct format. We cannot know the problem reported in the current issue. Please submit a new issue with you problem.
