### ISSUE TITLE
 client.messageManager.getHistoryMessageList

### ISSUE THREAD

**Issue by williamsim** [OpenIMSDK/Open-IM-SDK-Android#8]
获取不到历史消息

**Comment by hrxiang** [comment]
1，第一页startMsg传null，返回list
2，第二页startMsg传list.get(0)；其他页以此内推

**Comment by yuxiangxin** [comment]
> 获取不到历史消息

需要把OpenIMClient提供的各种监听都注册上, 不管是否需要.
